#!/bin/bash

case $1 in
init)
    terraform init
    exit 0
    ;;
plan)
    terraform plan
    exit 0
    ;;
create)
    terraform apply
    exit 0
    ;;
destroy)
    terraform destroy
    exit 0
    ;;
start)
    aws ec2 start-instances --region eu-west-2 --instance-ids $( terraform output id )
    exit 0
    ;;
stop)
    aws ec2 stop-instances --region eu-west-2 --instance-ids $( terraform output id )
    exit 0
    ;;
ssh)
    ssh $( terraform output ip ) -l centos -i ~/.ssh/id_rsa
    exit 0
    ;;
*)
    echo "Invalid usage"
    exit 1
    ;;
esac
